# Generated by Django 5.1.15 on 2026-06-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_add_variant_to_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="abandoned_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
