# Generated by Django 5.1.15 on 2026-06-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_newsletter_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
