from decimal import Decimal
from unittest import skipUnless
from unittest.mock import patch

from django.contrib.auth import get_user_model
from django.db import connection
from rest_framework import status
from rest_framework.test import APITestCase

from apps.catalog.models import Category, Product, Review, Warehouse, WarehouseStock, WishlistItem

User = get_user_model()

# Full-text search and trigram similarity are PostgreSQL-only. Off Postgres the
# search filter degrades to a substring match, so the typo/stemming assertions
# below are skipped (they can't pass on, e.g., SQLite).
POSTGRES = connection.vendor == "postgresql"


class CatalogReadTests(APITestCase):
    def setUp(self):
        self.category = Category.objects.create(name="Gadgets")
        self.product = Product.objects.create(
            category=self.category,
            name="Cool Widget",
            price=Decimal("10.00"),
            stock=5,
            sku="WID-1",
            description="A cool widget",
        )

    def test_list_products_is_public(self):
        res = self.client.get("/api/v1/products/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)

    def test_retrieve_product_by_slug(self):
        res = self.client.get(f"/api/v1/products/{self.product.slug}/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        self.assertEqual(res.data["name"], "Cool Widget")
        self.assertEqual(res.data["category_name"], "Gadgets")
        self.assertTrue(res.data["in_stock"])

    def test_slug_is_autogenerated(self):
        self.assertEqual(self.product.slug, "cool-widget")

    def test_search_products(self):
        Product.objects.create(
            category=self.category, name="Boring Thing", price=Decimal("5.00"),
            stock=1, sku="BOR-1",
        )
        res = self.client.get("/api/v1/products/?search=widget")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["name"], "Cool Widget")

    def test_search_returns_ok_on_any_engine(self):
        # Search must never 500: on Postgres it uses FTS/trigram, elsewhere it
        # falls back to a substring match. Either way the request succeeds.
        res = self.client.get("/api/v1/products/?search=widget")
        self.assertEqual(res.status_code, status.HTTP_200_OK)

    @skipUnless(POSTGRES, "Trigram typo tolerance requires PostgreSQL")
    def test_search_products_fuzzy_typo_tolerance(self):
        # Test that search is typo tolerant (e.g. "widgt" matches "Cool Widget")
        res = self.client.get("/api/v1/products/?search=widgt")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["name"], "Cool Widget")

    @skipUnless(POSTGRES, "Full-text stemming requires PostgreSQL")
    def test_search_products_stemming(self):
        # Test that search handles stemming (e.g. "widgets" matches "Cool Widget")
        res = self.client.get("/api/v1/products/?search=widgets")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["name"], "Cool Widget")

    def test_filter_by_category(self):
        other = Category.objects.create(name="Other")
        Product.objects.create(
            category=other, name="Other Item", price=Decimal("5.00"),
            stock=1, sku="OTH-1",
        )
        res = self.client.get(f"/api/v1/products/?category={self.category.id}")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)


class CatalogWriteTests(APITestCase):
    def setUp(self):
        self.category = Category.objects.create(name="Gadgets")
        self.user = User.objects.create_user(username="normal", password="pass12345", email="normal@test.com")
        self.admin = User.objects.create_superuser(username="admin", password="pass12345", email="admin@test.com")
        self.payload = {
            "category": self.category.id,
            "name": "New Widget",
            "price": "12.50",
            "stock": 3,
            "sku": "NEW-1",
        }

    def test_anonymous_cannot_create_product(self):
        res = self.client.post("/api/v1/products/", self.payload, format="json")
        self.assertIn(res.status_code, (status.HTTP_401_UNAUTHORIZED, status.HTTP_403_FORBIDDEN))
        self.assertEqual(Product.objects.count(), 0)

    def test_normal_user_cannot_create_product(self):
        self.client.force_authenticate(self.user)
        res = self.client.post("/api/v1/products/", self.payload, format="json")
        self.assertEqual(res.status_code, status.HTTP_403_FORBIDDEN)
        self.assertEqual(Product.objects.count(), 0)

    def test_admin_can_create_product(self):
        self.client.force_authenticate(self.admin)
        res = self.client.post("/api/v1/products/", self.payload, format="json")
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Product.objects.count(), 1)


class WishlistTests(APITestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username="wisher", password="strongpass123", email="wisher@test.com"
        )
        self.other = User.objects.create_user(
            username="other", password="strongpass123", email="other-wish@test.com"
        )
        self.cat = Category.objects.create(name="Test Category")
        self.prod = Product.objects.create(
            category=self.cat,
            name="Widget",
            slug="widget",
            price=19.99,
            stock=5,
            sku="WGT-001",
        )
        self.prod2 = Product.objects.create(
            category=self.cat,
            name="Gadget",
            slug="gadget",
            price=29.99,
            stock=3,
            sku="GGT-001",
        )
        self.list_url = "/api/v1/wishlist/"

    def test_unauthenticated_list_returns_401(self):
        res = self.client.get(self.list_url)
        self.assertEqual(res.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_unauthenticated_add_returns_401(self):
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        self.assertEqual(res.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_unauthenticated_delete_returns_401(self):
        res = self.client.delete(f"{self.list_url}1/")
        self.assertEqual(res.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_add_item_to_wishlist(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        self.assertEqual(WishlistItem.objects.count(), 1)
        self.assertEqual(
            WishlistItem.objects.first().user, self.user
        )

    def test_add_item_returns_product_fields(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        self.assertIn("product_name", res.data)
        self.assertEqual(res.data["product_name"], "Widget")
        self.assertIn("product_price", res.data)
        self.assertIn("product_slug", res.data)

    def test_duplicate_item_returns_400(self):
        self.client.force_authenticate(user=self.user)
        self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        self.assertEqual(res.status_code, status.HTTP_400_BAD_REQUEST)

    def test_add_nonexistent_product_returns_400(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(
            self.list_url, {"product": 99999}, format="json"
        )
        self.assertEqual(res.status_code, status.HTTP_400_BAD_REQUEST)

    def test_list_returns_users_items(self):
        self.client.force_authenticate(user=self.user)
        self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        self.client.post(self.list_url, {"product": self.prod2.id}, format="json")
        res = self.client.get(self.list_url)
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        results = res.data.get("results", res.data)
        self.assertEqual(len(results), 2)
        product_names = {r["product_name"] for r in results}
        self.assertIn("Widget", product_names)
        self.assertIn("Gadget", product_names)

    def test_list_isolation_between_users(self):
        self.client.force_authenticate(user=self.user)
        self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        self.client.force_authenticate(user=self.other)
        res = self.client.get(self.list_url)
        results = res.data.get("results", res.data)
        self.assertEqual(len(results), 0)

    def test_remove_item_from_wishlist(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        item_id = res.data["id"]
        res = self.client.delete(f"{self.list_url}{item_id}/")
        self.assertEqual(res.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(WishlistItem.objects.count(), 0)

    def test_remove_others_item_returns_404(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        item_id = res.data["id"]
        self.client.force_authenticate(user=self.other)
        res = self.client.delete(f"{self.list_url}{item_id}/")
        self.assertEqual(res.status_code, status.HTTP_404_NOT_FOUND)


class LowStockAlertTaskTests(APITestCase):
    def setUp(self):
        self.cat = Category.objects.create(name="Alerts")
        self.user_staff = User.objects.create_user(
            username="alertstaff", password="pass12345", email="staff_alert@test.com", is_staff=True
        )
        self.prod = Product.objects.create(
            category=self.cat,
            name="Base Product",
            price=Decimal("10.00"),
            stock=3,
            sku="BASE-SKU",
        )
        from apps.catalog.models import ProductVariant
        self.variant = ProductVariant.objects.create(
            product=self.prod,
            name="Variant Product",
            sku="VAR-SKU",
            price=Decimal("12.00"),
            stock=2,
        )

    @patch("apps.catalog.tasks.send_mail")
    def test_base_product_low_stock_email_sent(self, mock_send_mail):
        from apps.catalog.tasks import send_low_stock_alert_task
        send_low_stock_alert_task(self.prod.id)
        
        mock_send_mail.assert_called_once()
        kwargs = mock_send_mail.call_args[1]
        self.assertIn("Base Product", kwargs["subject"])
        self.assertIn("BASE-SKU", kwargs["message"])
        self.assertIn("staff_alert@test.com", kwargs["recipient_list"])

    @patch("apps.catalog.tasks.send_mail")
    def test_variant_low_stock_email_sent(self, mock_send_mail):
        from apps.catalog.tasks import send_low_stock_alert_task
        send_low_stock_alert_task(self.prod.id, variant_id=self.variant.id)
        
        mock_send_mail.assert_called_once()
        kwargs = mock_send_mail.call_args[1]
        self.assertIn("Base Product — Variant Product", kwargs["subject"])
        self.assertIn("VAR-SKU", kwargs["message"])
        self.assertIn("staff_alert@test.com", kwargs["recipient_list"])


class ReviewModerationTests(APITestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username="reviewer", password="pass12345", email="rev@test.com"
        )
        self.admin = User.objects.create_superuser(
            username="admin", password="pass12345", email="admin@test.com"
        )
        self.cat = Category.objects.create(name="Review Cat")
        self.product = Product.objects.create(
            category=self.cat, name="Reviewable", price=Decimal("15.00"),
            stock=5, sku="REV-001",
        )

    def test_new_review_defaults_to_pending(self):
        self.client.force_authenticate(self.user)
        res = self.client.post("/api/v1/reviews/", {
            "product": self.product.id, "rating": 5, "title": "Great", "body": "Love it",
        }, format="json")
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        self.assertEqual(res.data["status"], "pending")
        self.assertEqual(Review.objects.count(), 1)

    def test_public_list_excludes_pending_reviews(self):
        Review.objects.create(
            product=self.product, user=self.user, rating=4,
            title="Approved", status=Review.Status.APPROVED,
        )
        Review.objects.create(
            product=self.product, user=self.admin, rating=2,
            title="Pending", status=Review.Status.PENDING,
        )
        res = self.client.get(f"/api/v1/reviews/?product={self.product.id}")
        results = res.data["results"] if "results" in res.data else res.data
        titles = [r["title"] for r in results]
        self.assertIn("Approved", titles)
        self.assertNotIn("Pending", titles)

    def test_staff_sees_all_reviews(self):
        Review.objects.create(
            product=self.product, user=self.user, rating=4,
            title="Approved", status=Review.Status.APPROVED,
        )
        Review.objects.create(
            product=self.product, user=self.admin, rating=2,
            title="Pending", status=Review.Status.PENDING,
        )
        self.client.force_authenticate(self.admin)
        res = self.client.get(f"/api/v1/reviews/?product={self.product.id}")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 2)

    def test_staff_can_filter_by_status(self):
        Review.objects.create(
            product=self.product, user=self.user, rating=4,
            title="Approved", status=Review.Status.APPROVED,
        )
        Review.objects.create(
            product=self.product, user=self.admin, rating=2,
            title="Pending", status=Review.Status.PENDING,
        )
        self.client.force_authenticate(self.admin)
        res = self.client.get(f"/api/v1/reviews/?status=pending")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["title"], "Pending")

    def test_approve_action_sets_approved(self):
        review = Review.objects.create(
            product=self.product, user=self.user, rating=3,
            title="Needs Approval",
        )
        self.client.force_authenticate(self.admin)
        res = self.client.post(f"/api/v1/reviews/{review.id}/approve/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        review.refresh_from_db()
        self.assertEqual(review.status, Review.Status.APPROVED)

    def test_reject_action_sets_rejected(self):
        review = Review.objects.create(
            product=self.product, user=self.user, rating=3,
            title="Needs Rejection",
        )
        self.client.force_authenticate(self.admin)
        res = self.client.post(f"/api/v1/reviews/{review.id}/reject/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        review.refresh_from_db()
        self.assertEqual(review.status, Review.Status.REJECTED)

    def test_non_staff_cannot_approve(self):
        review = Review.objects.create(
            product=self.product, user=self.user, rating=3,
            title="Mine",
        )
        self.client.force_authenticate(self.user)
        res = self.client.post(f"/api/v1/reviews/{review.id}/approve/")
        self.assertEqual(res.status_code, status.HTTP_403_FORBIDDEN)

    def test_user_can_update_own_pending_review(self):
        review = Review.objects.create(
            product=self.product, user=self.user, rating=2,
            title="Old Title",
        )
        self.client.force_authenticate(self.user)
        res = self.client.patch(f"/api/v1/reviews/{review.id}/", {"title": "Updated"}, format="json")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        review.refresh_from_db()
        self.assertEqual(review.title, "Updated")
        # Status stays pending
        self.assertEqual(review.status, Review.Status.PENDING)


class WarehouseTests(APITestCase):
    def setUp(self):
        self.staff = User.objects.create_superuser("staff", "staff@test.com", "pass")
        self.user = User.objects.create_user("user", "user@test.com", "pass")
        self.category = Category.objects.create(name="Warehouse Test Cat")
        self.product = Product.objects.create(
            category=self.category, name="Test Product", price=Decimal("10.00"), stock=10, sku="WH-TP",
        )

    def test_non_staff_cannot_create_warehouse(self):
        self.client.force_authenticate(self.user)
        res = self.client.post("/api/v1/warehouses/", {"name": "X", "code": "X"}, format="json")
        self.assertEqual(res.status_code, status.HTTP_403_FORBIDDEN)

    def test_staff_can_create_warehouse(self):
        self.client.force_authenticate(self.staff)
        res = self.client.post(
            "/api/v1/warehouses/",
            {"name": "Main Warehouse", "code": "MAIN", "address": "123 Street"},
            format="json",
        )
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        # Migration 0010 seeds a default CENTRAL warehouse
        self.assertEqual(Warehouse.objects.count(), 2)

    def test_staff_can_list_warehouses(self):
        Warehouse.objects.create(name="A", code="A")
        Warehouse.objects.create(name="B", code="B")
        self.client.force_authenticate(self.staff)
        res = self.client.get("/api/v1/warehouses/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        # Migration 0010 seeds a default CENTRAL warehouse
        self.assertEqual(res.data["count"], 3)

    def test_staff_can_update_warehouse(self):
        w = Warehouse.objects.create(name="Old", code="OLD")
        self.client.force_authenticate(self.staff)
        res = self.client.patch(f"/api/v1/warehouses/{w.id}/", {"name": "New"}, format="json")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        w.refresh_from_db()
        self.assertEqual(w.name, "New")

    def test_staff_can_delete_warehouse(self):
        w = Warehouse.objects.create(name="Temp", code="TMP")
        self.client.force_authenticate(self.staff)
        res = self.client.delete(f"/api/v1/warehouses/{w.id}/")
        self.assertEqual(res.status_code, status.HTTP_204_NO_CONTENT)
        # Only the seeded CENTRAL warehouse remains
        self.assertEqual(Warehouse.objects.count(), 1)

    def test_staff_can_create_warehouse_stock(self):
        w = Warehouse.objects.create(name="W", code="W")
        self.client.force_authenticate(self.staff)
        res = self.client.post(
            "/api/v1/warehouse-stocks/",
            {"warehouse": w.id, "product": self.product.id, "stock": 50, "variant": None},
            format="json",
        )
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        # The product was created after migration, so only 1 stock entry
        self.assertEqual(WarehouseStock.objects.count(), 1)

    def test_staff_can_update_warehouse_stock(self):
        central = Warehouse.objects.get(code="CENTRAL")
        ws = WarehouseStock.objects.create(warehouse=central, product=self.product, stock=10)
        self.client.force_authenticate(self.staff)
        res = self.client.patch(f"/api/v1/warehouse-stocks/{ws.id}/", {"stock": 99}, format="json")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        ws.refresh_from_db()
        self.assertEqual(ws.stock, 99)

    def test_warehouse_stock_filter_by_warehouse(self):
        w1 = Warehouse.objects.create(name="W1", code="W1")
        w2 = Warehouse.objects.create(name="W2", code="W2")
        WarehouseStock.objects.create(warehouse=w1, product=self.product, stock=5)
        central = Warehouse.objects.get(code="CENTRAL")
        WarehouseStock.objects.create(warehouse=w2, product=self.product, stock=10)
        self.client.force_authenticate(self.staff)
        res = self.client.get(f"/api/v1/warehouse-stocks/?warehouse={w1.id}")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        # Only the stock entry for w1 (excludes CENTRAL seed + w2)
        self.assertEqual(res.data["count"], 1)
