from decimal import Decimal
from unittest import skipUnless
from unittest.mock import patch

from django.contrib.auth import get_user_model
from django.db import connection
from rest_framework import status
from rest_framework.test import APITestCase

from apps.catalog.models import Category, Product, Review, Warehouse, WarehouseStock, WishlistItem

User = get_user_model()

# Full-text search and trigram similarity are PostgreSQL-only. Off Postgres the
# search filter degrades to a substring match, so the typo/stemming assertions
# below are skipped (they can't pass on, e.g., SQLite).
POSTGRES = connection.vendor == "postgresql"


class CatalogReadTests(APITestCase):
    def setUp(self):
        self.category = Category.objects.create(name="Gadgets")
        self.product = Product.objects.create(
            category=self.category,
            name="Cool Widget",
            price=Decimal("10.00"),
            stock=5,
            sku="WID-1",
            description="A cool widget",
        )

    def test_list_products_is_public(self):
        res = self.client.get("/api/v1/products/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)

    def test_retrieve_product_by_slug(self):
        res = self.client.get(f"/api/v1/products/{self.product.slug}/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        self.assertEqual(res.data["name"], "Cool Widget")
        self.assertEqual(res.data["category_name"], "Gadgets")
        self.assertTrue(res.data["in_stock"])

    def test_slug_is_autogenerated(self):
        self.assertEqual(self.product.slug, "cool-widget")

    def test_search_products(self):
        Product.objects.create(
            category=self.category,
            name="Boring Thing",
            price=Decimal("5.00"),
            stock=1,
            sku="BOR-1",
        )
        res = self.client.get("/api/v1/products/?search=widget")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["name"], "Cool Widget")

    def test_search_returns_ok_on_any_engine(self):
        # Search must never 500: on Postgres it uses FTS/trigram, elsewhere it
        # falls back to a substring match. Either way the request succeeds.
        res = self.client.get("/api/v1/products/?search=widget")
        self.assertEqual(res.status_code, status.HTTP_200_OK)

    @skipUnless(POSTGRES, "Trigram typo tolerance requires PostgreSQL")
    def test_search_products_fuzzy_typo_tolerance(self):
        # Test that search is typo tolerant (e.g. "widgt" matches "Cool Widget")
        res = self.client.get("/api/v1/products/?search=widgt")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["name"], "Cool Widget")

    @skipUnless(POSTGRES, "Full-text stemming requires PostgreSQL")
    def test_search_products_stemming(self):
        # Test that search handles stemming (e.g. "widgets" matches "Cool Widget")
        res = self.client.get("/api/v1/products/?search=widgets")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["name"], "Cool Widget")

    def test_filter_by_category(self):
        other = Category.objects.create(name="Other")
        Product.objects.create(
            category=other,
            name="Other Item",
            price=Decimal("5.00"),
            stock=1,
            sku="OTH-1",
        )
        res = self.client.get(f"/api/v1/products/?category={self.category.id}")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)


class CatalogWriteTests(APITestCase):
    def setUp(self):
        self.category = Category.objects.create(name="Gadgets")
        self.user = User.objects.create_user(
            username="normal", password="pass12345", email="normal@test.com"
        )
        self.admin = User.objects.create_superuser(
            username="admin", password="pass12345", email="admin@test.com"
        )
        self.payload = {
            "category": self.category.id,
            "name": "New Widget",
            "price": "12.50",
            "stock": 3,
            "sku": "NEW-1",
        }

    def test_anonymous_cannot_create_product(self):
        res = self.client.post("/api/v1/products/", self.payload, format="json")
        self.assertIn(res.status_code, (status.HTTP_401_UNAUTHORIZED, status.HTTP_403_FORBIDDEN))
        self.assertEqual(Product.objects.count(), 0)

    def test_normal_user_cannot_create_product(self):
        self.client.force_authenticate(self.user)
        res = self.client.post("/api/v1/products/", self.payload, format="json")
        self.assertEqual(res.status_code, status.HTTP_403_FORBIDDEN)
        self.assertEqual(Product.objects.count(), 0)

    def test_admin_can_create_product(self):
        self.client.force_authenticate(self.admin)
        res = self.client.post("/api/v1/products/", self.payload, format="json")
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Product.objects.count(), 1)


class WishlistTests(APITestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username="wisher", password="strongpass123", email="wisher@test.com"
        )
        self.other = User.objects.create_user(
            username="other", password="strongpass123", email="other-wish@test.com"
        )
        self.cat = Category.objects.create(name="Test Category")
        self.prod = Product.objects.create(
            category=self.cat,
            name="Widget",
            slug="widget",
            price=19.99,
            stock=5,
            sku="WGT-001",
        )
        self.prod2 = Product.objects.create(
            category=self.cat,
            name="Gadget",
            slug="gadget",
            price=29.99,
            stock=3,
            sku="GGT-001",
        )
        self.list_url = "/api/v1/wishlist/"

    def test_unauthenticated_list_returns_401(self):
        res = self.client.get(self.list_url)
        self.assertEqual(res.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_unauthenticated_add_returns_401(self):
        res = self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        self.assertEqual(res.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_unauthenticated_delete_returns_401(self):
        res = self.client.delete(f"{self.list_url}1/")
        self.assertEqual(res.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_add_item_to_wishlist(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        self.assertEqual(WishlistItem.objects.count(), 1)
        self.assertEqual(WishlistItem.objects.first().user, self.user)

    def test_add_item_returns_product_fields(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        self.assertIn("product_name", res.data)
        self.assertEqual(res.data["product_name"], "Widget")
        self.assertIn("product_price", res.data)
        self.assertIn("product_slug", res.data)

    def test_duplicate_item_returns_400(self):
        self.client.force_authenticate(user=self.user)
        self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        res = self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        self.assertEqual(res.status_code, status.HTTP_400_BAD_REQUEST)

    def test_add_nonexistent_product_returns_400(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(self.list_url, {"product": 99999}, format="json")
        self.assertEqual(res.status_code, status.HTTP_400_BAD_REQUEST)

    def test_list_returns_users_items(self):
        self.client.force_authenticate(user=self.user)
        self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        self.client.post(self.list_url, {"product": self.prod2.id}, format="json")
        res = self.client.get(self.list_url)
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        results = res.data.get("results", res.data)
        self.assertEqual(len(results), 2)
        product_names = {r["product_name"] for r in results}
        self.assertIn("Widget", product_names)
        self.assertIn("Gadget", product_names)

    def test_list_isolation_between_users(self):
        self.client.force_authenticate(user=self.user)
        self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        self.client.force_authenticate(user=self.other)
        res = self.client.get(self.list_url)
        results = res.data.get("results", res.data)
        self.assertEqual(len(results), 0)

    def test_remove_item_from_wishlist(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        item_id = res.data["id"]
        res = self.client.delete(f"{self.list_url}{item_id}/")
        self.assertEqual(res.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(WishlistItem.objects.count(), 0)

    def test_remove_others_item_returns_404(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        item_id = res.data["id"]
        self.client.force_authenticate(user=self.other)
        res = self.client.delete(f"{self.list_url}{item_id}/")
        self.assertEqual(res.status_code, status.HTTP_404_NOT_FOUND)


class LowStockAlertTaskTests(APITestCase):
    def setUp(self):
        self.cat = Category.objects.create(name="Alerts")
        self.user_staff = User.objects.create_user(
            username="alertstaff", password="pass12345", email="staff_alert@test.com", is_staff=True
        )
        self.prod = Product.objects.create(
            category=self.cat,
            name="Base Product",
            price=Decimal("10.00"),
            stock=3,
            sku="BASE-SKU",
        )
        from apps.catalog.models import ProductVariant

        self.variant = ProductVariant.objects.create(
            product=self.prod,
            name="Variant Product",
            sku="VAR-SKU",
            price=Decimal("12.00"),
            stock=2,
        )

    @patch("apps.catalog.tasks.send_html_email")
    def test_base_product_low_stock_email_sent(self, mock_send_mail):
        from apps.catalog.tasks import send_low_stock_alert_task

        send_low_stock_alert_task(self.prod.id)

        mock_send_mail.assert_called_once()
        kwargs = mock_send_mail.call_args[1]
        self.assertIn("Base Product", kwargs["subject"])
        self.assertIn("BASE-SKU", kwargs["text_body"])
        self.assertIn("staff_alert@test.com", kwargs["recipient_list"])

    @patch("apps.catalog.tasks.send_html_email")
    def test_variant_low_stock_email_sent(self, mock_send_mail):
        from apps.catalog.tasks import send_low_stock_alert_task

        send_low_stock_alert_task(self.prod.id, variant_id=self.variant.id)

        mock_send_mail.assert_called_once()
        kwargs = mock_send_mail.call_args[1]
        self.assertIn("Base Product — Variant Product", kwargs["subject"])
        self.assertIn("VAR-SKU", kwargs["text_body"])
        self.assertIn("staff_alert@test.com", kwargs["recipient_list"])


class ReviewModerationTests(APITestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username="reviewer", password="pass12345", email="rev@test.com"
        )
        self.admin = User.objects.create_superuser(
            username="admin", password="pass12345", email="admin@test.com"
        )
        self.cat = Category.objects.create(name="Review Cat")
        self.product = Product.objects.create(
            category=self.cat,
            name="Reviewable",
            price=Decimal("15.00"),
            stock=5,
            sku="REV-001",
        )

    def test_new_review_defaults_to_pending(self):
        self.client.force_authenticate(self.user)
        res = self.client.post(
            "/api/v1/reviews/",
            {
                "product": self.product.id,
                "rating": 5,
                "title": "Great",
                "body": "Love it",
            },
            format="json",
        )
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        self.assertEqual(res.data["status"], "pending")
        self.assertEqual(Review.objects.count(), 1)

    def test_public_list_excludes_pending_reviews(self):
        Review.objects.create(
            product=self.product,
            user=self.user,
            rating=4,
            title="Approved",
            status=Review.Status.APPROVED,
        )
        Review.objects.create(
            product=self.product,
            user=self.admin,
            rating=2,
            title="Pending",
            status=Review.Status.PENDING,
        )
        res = self.client.get(f"/api/v1/reviews/?product={self.product.id}")
        results = res.data["results"] if "results" in res.data else res.data
        titles = [r["title"] for r in results]
        self.assertIn("Approved", titles)
        self.assertNotIn("Pending", titles)

    def test_staff_sees_all_reviews(self):
        Review.objects.create(
            product=self.product,
            user=self.user,
            rating=4,
            title="Approved",
            status=Review.Status.APPROVED,
        )
        Review.objects.create(
            product=self.product,
            user=self.admin,
            rating=2,
            title="Pending",
            status=Review.Status.PENDING,
        )
        self.client.force_authenticate(self.admin)
        res = self.client.get(f"/api/v1/reviews/?product={self.product.id}")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 2)

    def test_staff_can_filter_by_status(self):
        Review.objects.create(
            product=self.product,
            user=self.user,
            rating=4,
            title="Approved",
            status=Review.Status.APPROVED,
        )
        Review.objects.create(
            product=self.product,
            user=self.admin,
            rating=2,
            title="Pending",
            status=Review.Status.PENDING,
        )
        self.client.force_authenticate(self.admin)
        res = self.client.get(f"/api/v1/reviews/?status=pending")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["title"], "Pending")

    def test_approve_action_sets_approved(self):
        review = Review.objects.create(
            product=self.product,
            user=self.user,
            rating=3,
            title="Needs Approval",
        )
        self.client.force_authenticate(self.admin)
        res = self.client.post(f"/api/v1/reviews/{review.id}/approve/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        review.refresh_from_db()
        self.assertEqual(review.status, Review.Status.APPROVED)

    def test_reject_action_sets_rejected(self):
        review = Review.objects.create(
            product=self.product,
            user=self.user,
            rating=3,
            title="Needs Rejection",
        )
        self.client.force_authenticate(self.admin)
        res = self.client.post(f"/api/v1/reviews/{review.id}/reject/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        review.refresh_from_db()
        self.assertEqual(review.status, Review.Status.REJECTED)

    def test_non_staff_cannot_approve(self):
        review = Review.objects.create(
            product=self.product,
            user=self.user,
            rating=3,
            title="Mine",
        )
        self.client.force_authenticate(self.user)
        res = self.client.post(f"/api/v1/reviews/{review.id}/approve/")
        self.assertEqual(res.status_code, status.HTTP_403_FORBIDDEN)

    def test_user_can_update_own_pending_review(self):
        review = Review.objects.create(
            product=self.product,
            user=self.user,
            rating=2,
            title="Old Title",
        )
        self.client.force_authenticate(self.user)
        res = self.client.patch(
            f"/api/v1/reviews/{review.id}/", {"title": "Updated"}, format="json"
        )
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        review.refresh_from_db()
        self.assertEqual(review.title, "Updated")
        # Status stays pending
        self.assertEqual(review.status, Review.Status.PENDING)


class WarehouseTests(APITestCase):
    def setUp(self):
        self.staff = User.objects.create_superuser("staff", "staff@test.com", "pass")
        self.user = User.objects.create_user("user", "user@test.com", "pass")
        self.category = Category.objects.create(name="Warehouse Test Cat")
        self.product = Product.objects.create(
            category=self.category,
            name="Test Product",
            price=Decimal("10.00"),
            stock=10,
            sku="WH-TP",
        )

    def test_non_staff_cannot_create_warehouse(self):
        self.client.force_authenticate(self.user)
        res = self.client.post("/api/v1/warehouses/", {"name": "X", "code": "X"}, format="json")
        self.assertEqual(res.status_code, status.HTTP_403_FORBIDDEN)

    def test_staff_can_create_warehouse(self):
        self.client.force_authenticate(self.staff)
        res = self.client.post(
            "/api/v1/warehouses/",
            {"name": "Main Warehouse", "code": "MAIN", "address": "123 Street"},
            format="json",
        )
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        # Migration 0010 seeds a default CENTRAL warehouse
        self.assertEqual(Warehouse.objects.count(), 2)

    def test_staff_can_list_warehouses(self):
        Warehouse.objects.create(name="A", code="A")
        Warehouse.objects.create(name="B", code="B")
        self.client.force_authenticate(self.staff)
        res = self.client.get("/api/v1/warehouses/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        # Migration 0010 seeds a default CENTRAL warehouse
        self.assertEqual(res.data["count"], 3)

    def test_staff_can_update_warehouse(self):
        w = Warehouse.objects.create(name="Old", code="OLD")
        self.client.force_authenticate(self.staff)
        res = self.client.patch(f"/api/v1/warehouses/{w.id}/", {"name": "New"}, format="json")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        w.refresh_from_db()
        self.assertEqual(w.name, "New")

    def test_staff_can_delete_warehouse(self):
        w = Warehouse.objects.create(name="Temp", code="TMP")
        self.client.force_authenticate(self.staff)
        res = self.client.delete(f"/api/v1/warehouses/{w.id}/")
        self.assertEqual(res.status_code, status.HTTP_204_NO_CONTENT)
        # Only the seeded CENTRAL warehouse remains
        self.assertEqual(Warehouse.objects.count(), 1)

    def test_staff_can_create_warehouse_stock(self):
        w = Warehouse.objects.create(name="W", code="W")
        self.client.force_authenticate(self.staff)
        res = self.client.post(
            "/api/v1/warehouse-stocks/",
            {"warehouse": w.id, "product": self.product.id, "stock": 50, "variant": None},
            format="json",
        )
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        # The product was created after migration, so only 1 stock entry
        self.assertEqual(WarehouseStock.objects.count(), 1)

    def test_staff_can_update_warehouse_stock(self):
        central = Warehouse.objects.get(code="CENTRAL")
        ws = WarehouseStock.objects.create(warehouse=central, product=self.product, stock=10)
        self.client.force_authenticate(self.staff)
        res = self.client.patch(f"/api/v1/warehouse-stocks/{ws.id}/", {"stock": 99}, format="json")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        ws.refresh_from_db()
        self.assertEqual(ws.stock, 99)

    def test_warehouse_stock_filter_by_warehouse(self):
        w1 = Warehouse.objects.create(name="W1", code="W1")
        w2 = Warehouse.objects.create(name="W2", code="W2")
        WarehouseStock.objects.create(warehouse=w1, product=self.product, stock=5)
        central = Warehouse.objects.get(code="CENTRAL")
        WarehouseStock.objects.create(warehouse=w2, product=self.product, stock=10)
        self.client.force_authenticate(self.staff)
        res = self.client.get(f"/api/v1/warehouse-stocks/?warehouse={w1.id}")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        # Only the stock entry for w1 (excludes CENTRAL seed + w2)
        self.assertEqual(res.data["count"], 1)


class RelatedProductsTests(APITestCase):
    def setUp(self):
        self.category = Category.objects.create(name="Tech")
        self.other_cat = Category.objects.create(name="Books")
        self.product = Product.objects.create(
            category=self.category,
            name="Main Product",
            price=Decimal("20.00"),
            stock=5,
            sku="MAIN-01",
        )
        # 3 related products in same category
        self.related = []
        for i in range(3):
            p = Product.objects.create(
                category=self.category,
                name=f"Related {i}",
                price=Decimal(f"{10 + i}.00"),
                stock=3,
                sku=f"REL-{i:02d}",
            )
            self.related.append(p)
        # 1 product in different category (should NOT be related)
        self.unrelated = Product.objects.create(
            category=self.other_cat,
            name="Unrelated",
            price=Decimal("15.00"),
            stock=2,
            sku="UNREL-01",
        )

    def test_related_returns_same_category_products(self):
        res = self.client.get(f"/api/v1/products/{self.product.slug}/related/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        slugs = {p["slug"] for p in res.data}
        for p in self.related:
            self.assertIn(p.slug, slugs)
        self.assertNotIn(self.unrelated.slug, slugs)
        self.assertNotIn(self.product.slug, slugs)

    def test_related_excludes_current_product(self):
        res = self.client.get(f"/api/v1/products/{self.product.slug}/related/")
        slugs = {p["slug"] for p in res.data}
        self.assertNotIn(self.product.slug, slugs)

    def test_related_returns_max_four(self):
        # Add a 4th product to same category
        Product.objects.create(
            category=self.category,
            name="Related 4",
            price=Decimal("14.00"),
            stock=3,
            sku="REL-04",
        )
        Product.objects.create(
            category=self.category,
            name="Related 5",
            price=Decimal("15.00"),
            stock=3,
            sku="REL-05",
        )
        res = self.client.get(f"/api/v1/products/{self.product.slug}/related/")
        self.assertLessEqual(len(res.data), 4)

    def test_related_empty_when_alone_in_category(self):
        empty_cat = Category.objects.create(name="Empty Cat")
        lone = Product.objects.create(
            category=empty_cat,
            name="Lone Wolf",
            price=Decimal("99.00"),
            stock=1,
            sku="LONE-01",
        )
        res = self.client.get(f"/api/v1/products/{lone.slug}/related/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        self.assertEqual(len(res.data), 0)

    def test_related_is_publicly_accessible(self):
        res = self.client.get(f"/api/v1/products/{self.product.slug}/related/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)

    def test_related_returns_serialized_with_ratings(self):
        # Add a review to one of the related products
        user = get_user_model().objects.create_user("rater", "rater@test.com", "pass")
        from apps.catalog.models import Review

        rated = self.related[0]
        Review.objects.create(
            product=rated,
            user=user,
            rating=5,
            title="Great",
            status=Review.Status.APPROVED,
        )
        res = self.client.get(f"/api/v1/products/{self.product.slug}/related/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        # The rated product should be among results with correct fields
        rated_result = next(p for p in res.data if p["slug"] == rated.slug)
        self.assertEqual(rated_result["avg_rating"], 5.0)
        self.assertEqual(rated_result["review_count"], 1)


class ProductFlagsTests(APITestCase):
    def setUp(self):
        self.staff = User.objects.create_superuser("staff", "staff@test.com", "pass")
        self.user = User.objects.create_user("user", "user@test.com", "pass")
        self.category = Category.objects.create(name="Flags Cat")
        self.product = Product.objects.create(
            category=self.category,
            name="Base",
            price=Decimal("20.00"),
            stock=5,
            sku="FLAG-01",
        )

    def test_effective_price_returns_price_when_not_on_sale(self):
        self.assertEqual(self.product.effective_price, Decimal("20.00"))

    def test_effective_price_returns_sale_price_when_on_sale(self):
        self.product.on_sale = True
        self.product.sale_price = Decimal("15.00")
        self.product.save()
        self.assertEqual(self.product.effective_price, Decimal("15.00"))

    def test_display_badge_returns_none_by_default(self):
        self.assertIsNone(self.product.display_badge)

    def test_display_badge_returns_new_when_is_new(self):
        self.product.is_new = True
        self.product.save()
        self.assertEqual(self.product.display_badge, "New")

    def test_display_badge_returns_sale_when_on_sale(self):
        self.product.on_sale = True
        self.product.sale_price = Decimal("15.00")
        self.product.save()
        self.assertEqual(self.product.display_badge, "Sale")

    def test_display_badge_prefers_custom_over_auto(self):
        self.product.is_new = True
        self.product.badge = "Limited"
        self.product.save()
        self.assertEqual(self.product.display_badge, "Limited")

    def test_filter_by_is_featured(self):
        Product.objects.create(
            category=self.category,
            name="Featured",
            price=10,
            stock=1,
            sku="FEAT-01",
            is_featured=True,
        )
        Product.objects.create(
            category=self.category,
            name="Normal",
            price=10,
            stock=1,
            sku="NORM-01",
            is_featured=False,
        )
        self.client.force_authenticate(self.staff)
        res = self.client.get("/api/v1/products/?is_featured=true")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        names = [p["name"] for p in res.data["results"]]
        self.assertIn("Featured", names)
        self.assertNotIn("Normal", names)

    def test_serializer_exposes_new_fields(self):
        self.product.is_featured = True
        self.product.is_new = True
        self.product.on_sale = True
        self.product.sale_price = Decimal("15.00")
        self.product.badge = "Clearance"
        self.product.save()
        self.client.force_authenticate(self.staff)
        res = self.client.get(f"/api/v1/products/{self.product.slug}/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        self.assertTrue(res.data["is_featured"])
        self.assertTrue(res.data["is_new"])
        self.assertTrue(res.data["on_sale"])
        self.assertEqual(res.data["sale_price"], "15.00")
        self.assertEqual(res.data["badge"], "Clearance")
        self.assertEqual(res.data["display_badge"], "Clearance")
        self.assertEqual(res.data["effective_price"], "15.00")


class WarehouseStockEdgeCaseTests(APITestCase):
    """Edge cases for warehouse stock management."""

    def setUp(self):
        self.category = Category.objects.create(name="WH Edge")
        self.product = Product.objects.create(
            category=self.category,
            name="WH Product",
            price=Decimal("10.00"),
            sku="WH-EDGE-1",
            stock=5,
        )

    def test_no_active_warehouses_auto_creates_central(self):
        """When no active warehouses exist, create_order_and_items self-heals."""
        from apps.orders.services import create_order_and_items

        Warehouse.objects.all().delete()

        order_kwargs = {
            "shipping_full_name": "Test",
            "shipping_address": "123 St",
            "shipping_city": "City",
            "shipping_postal_code": "12345",
            "shipping_country": "US",
        }
        order, _ = create_order_and_items(
            order_kwargs={**order_kwargs, "user": None, "guest_email": "nowh@test.com"},
            items=[{"product_id": self.product.id, "quantity": 1}],
        )
        self.assertIsNotNone(order.warehouse)
        self.assertEqual(order.warehouse.code, "CENTRAL")

    def test_deactivated_warehouse_skipped_for_fulfillment(self):
        """Deactivated warehouses should not be selected for order fulfillment."""
        from apps.catalog.models import Warehouse, WarehouseStock
        from apps.orders.services import create_order_and_items

        Warehouse.objects.all().delete()
        wh_active = Warehouse.objects.create(name="Active WH", code="ACTV", is_active=True)
        wh_inactive = Warehouse.objects.create(name="Inactive WH", code="NOPE", is_active=False)
        WarehouseStock.objects.create(warehouse=wh_inactive, product=self.product, stock=10)
        WarehouseStock.objects.create(warehouse=wh_active, product=self.product, stock=3)

        order_kwargs = {
            "shipping_full_name": "Test",
            "shipping_address": "123 St",
            "shipping_city": "City",
            "shipping_postal_code": "12345",
            "shipping_country": "US",
        }
        items = [{"product_id": self.product.id, "quantity": 3}]
        order, _ = create_order_and_items(
            order_kwargs={**order_kwargs, "user": None, "guest_email": "deact@test.com"},
            items=items,
        )
        # Should pick active WH (stock=3) even though inactive has 10
        self.assertEqual(order.warehouse, wh_active)

    def test_exact_warehouse_stock_succeeds(self):
        """Ordering exactly the available stock in a warehouse succeeds."""
        from apps.catalog.models import Warehouse, WarehouseStock
        from apps.orders.services import create_order_and_items

        Warehouse.objects.all().delete()
        wh = Warehouse.objects.create(name="Exact WH", code="EXACT", is_active=True)
        WarehouseStock.objects.create(warehouse=wh, product=self.product, stock=5)

        order_kwargs = {
            "shipping_full_name": "Exact Test",
            "shipping_address": "5 Exact St",
            "shipping_city": "Exact",
            "shipping_postal_code": "55555",
            "shipping_country": "US",
        }
        order, _ = create_order_and_items(
            order_kwargs={**order_kwargs, "user": None, "guest_email": "exact@test.com"},
            items=[{"product_id": self.product.id, "quantity": 5}],
        )
        self.assertEqual(order.items.count(), 1)

    def test_order_exceeding_all_warehouse_stock_raises_error(self):
        """Ordering more than total available across all warehouses fails."""
        from apps.catalog.models import Warehouse, WarehouseStock
        from apps.orders.models import Order
        from apps.orders.services import CheckoutError, create_order_and_items

        Warehouse.objects.all().delete()
        wh = Warehouse.objects.create(name="Limited WH", code="LIMIT", is_active=True)
        WarehouseStock.objects.create(warehouse=wh, product=self.product, stock=3)

        order_kwargs = {
            "shipping_full_name": "Over Test",
            "shipping_address": "99 Over St",
            "shipping_city": "Over",
            "shipping_postal_code": "99999",
            "shipping_country": "US",
        }
        with self.assertRaises(CheckoutError):
            create_order_and_items(
                order_kwargs={**order_kwargs, "user": None, "guest_email": "overwh@test.com"},
                items=[{"product_id": self.product.id, "quantity": 5}],
            )
        self.assertEqual(Order.objects.count(), 0)

    def test_warehouse_stock_filter_by_warehouse(self):
        """Warehouse stock endpoint filters correctly by warehouse."""
        from apps.catalog.models import Warehouse, WarehouseStock

        User = get_user_model()
        staff = User.objects.create_superuser("whstaff", "wh@test.com", "pass")
        self.client.force_authenticate(staff)

        wh1 = Warehouse.objects.create(name="Filter WH A", code="FILA", is_active=True)
        wh2 = Warehouse.objects.create(name="Filter WH B", code="FILB", is_active=True)
        WarehouseStock.objects.create(warehouse=wh1, product=self.product, stock=5)
        WarehouseStock.objects.create(warehouse=wh2, product=self.product, stock=10)

        res = self.client.get(f"/api/v1/warehouse-stocks/?warehouse={wh1.id}")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["stock"], 5)
