from decimal import Decimal

from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.test import APITestCase

from apps.catalog.models import Category, Product, WishlistItem

User = get_user_model()


class CatalogReadTests(APITestCase):
    def setUp(self):
        self.category = Category.objects.create(name="Gadgets")
        self.product = Product.objects.create(
            category=self.category,
            name="Cool Widget",
            price=Decimal("10.00"),
            stock=5,
            sku="WID-1",
            description="A cool widget",
        )

    def test_list_products_is_public(self):
        res = self.client.get("/api/products/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)

    def test_retrieve_product_by_slug(self):
        res = self.client.get(f"/api/products/{self.product.slug}/")
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        self.assertEqual(res.data["name"], "Cool Widget")
        self.assertEqual(res.data["category_name"], "Gadgets")
        self.assertTrue(res.data["in_stock"])

    def test_slug_is_autogenerated(self):
        self.assertEqual(self.product.slug, "cool-widget")

    def test_search_products(self):
        Product.objects.create(
            category=self.category, name="Boring Thing", price=Decimal("5.00"),
            stock=1, sku="BOR-1",
        )
        res = self.client.get("/api/products/?search=widget")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["name"], "Cool Widget")

    def test_search_products_fuzzy_typo_tolerance(self):
        # Test that search is typo tolerant (e.g. "widgt" matches "Cool Widget")
        res = self.client.get("/api/products/?search=widgt")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["name"], "Cool Widget")

    def test_search_products_stemming(self):
        # Test that search handles stemming (e.g. "widgets" matches "Cool Widget")
        res = self.client.get("/api/products/?search=widgets")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]["name"], "Cool Widget")

    def test_filter_by_category(self):
        other = Category.objects.create(name="Other")
        Product.objects.create(
            category=other, name="Other Item", price=Decimal("5.00"),
            stock=1, sku="OTH-1",
        )
        res = self.client.get(f"/api/products/?category={self.category.id}")
        results = res.data["results"] if "results" in res.data else res.data
        self.assertEqual(len(results), 1)


class CatalogWriteTests(APITestCase):
    def setUp(self):
        self.category = Category.objects.create(name="Gadgets")
        self.user = User.objects.create_user(username="normal", password="pass12345", email="normal@test.com")
        self.admin = User.objects.create_superuser(username="admin", password="pass12345", email="admin@test.com")
        self.payload = {
            "category": self.category.id,
            "name": "New Widget",
            "price": "12.50",
            "stock": 3,
            "sku": "NEW-1",
        }

    def test_anonymous_cannot_create_product(self):
        res = self.client.post("/api/products/", self.payload, format="json")
        self.assertIn(res.status_code, (status.HTTP_401_UNAUTHORIZED, status.HTTP_403_FORBIDDEN))
        self.assertEqual(Product.objects.count(), 0)

    def test_normal_user_cannot_create_product(self):
        self.client.force_authenticate(self.user)
        res = self.client.post("/api/products/", self.payload, format="json")
        self.assertEqual(res.status_code, status.HTTP_403_FORBIDDEN)
        self.assertEqual(Product.objects.count(), 0)

    def test_admin_can_create_product(self):
        self.client.force_authenticate(self.admin)
        res = self.client.post("/api/products/", self.payload, format="json")
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Product.objects.count(), 1)


class WishlistTests(APITestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username="wisher", password="strongpass123", email="wisher@test.com"
        )
        self.other = User.objects.create_user(
            username="other", password="strongpass123", email="other-wish@test.com"
        )
        self.cat = Category.objects.create(name="Test Category")
        self.prod = Product.objects.create(
            category=self.cat,
            name="Widget",
            slug="widget",
            price=19.99,
            stock=5,
            sku="WGT-001",
        )
        self.prod2 = Product.objects.create(
            category=self.cat,
            name="Gadget",
            slug="gadget",
            price=29.99,
            stock=3,
            sku="GGT-001",
        )
        self.list_url = "/api/wishlist/"

    def test_unauthenticated_list_returns_401(self):
        res = self.client.get(self.list_url)
        self.assertEqual(res.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_unauthenticated_add_returns_401(self):
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        self.assertEqual(res.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_unauthenticated_delete_returns_401(self):
        res = self.client.delete(f"{self.list_url}1/")
        self.assertEqual(res.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_add_item_to_wishlist(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        self.assertEqual(WishlistItem.objects.count(), 1)
        self.assertEqual(
            WishlistItem.objects.first().user, self.user
        )

    def test_add_item_returns_product_fields(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        self.assertIn("product_name", res.data)
        self.assertEqual(res.data["product_name"], "Widget")
        self.assertIn("product_price", res.data)
        self.assertIn("product_slug", res.data)

    def test_duplicate_item_returns_400(self):
        self.client.force_authenticate(user=self.user)
        self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        self.assertEqual(res.status_code, status.HTTP_400_BAD_REQUEST)

    def test_add_nonexistent_product_returns_400(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(
            self.list_url, {"product": 99999}, format="json"
        )
        self.assertEqual(res.status_code, status.HTTP_400_BAD_REQUEST)

    def test_list_returns_users_items(self):
        self.client.force_authenticate(user=self.user)
        self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        self.client.post(self.list_url, {"product": self.prod2.id}, format="json")
        res = self.client.get(self.list_url)
        self.assertEqual(res.status_code, status.HTTP_200_OK)
        results = res.data.get("results", res.data)
        self.assertEqual(len(results), 2)
        product_names = {r["product_name"] for r in results}
        self.assertIn("Widget", product_names)
        self.assertIn("Gadget", product_names)

    def test_list_isolation_between_users(self):
        self.client.force_authenticate(user=self.user)
        self.client.post(self.list_url, {"product": self.prod.id}, format="json")
        self.client.force_authenticate(user=self.other)
        res = self.client.get(self.list_url)
        results = res.data.get("results", res.data)
        self.assertEqual(len(results), 0)

    def test_remove_item_from_wishlist(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        item_id = res.data["id"]
        res = self.client.delete(f"{self.list_url}{item_id}/")
        self.assertEqual(res.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(WishlistItem.objects.count(), 0)

    def test_remove_others_item_returns_404(self):
        self.client.force_authenticate(user=self.user)
        res = self.client.post(
            self.list_url, {"product": self.prod.id}, format="json"
        )
        item_id = res.data["id"]
        self.client.force_authenticate(user=self.other)
        res = self.client.delete(f"{self.list_url}{item_id}/")
        self.assertEqual(res.status_code, status.HTTP_404_NOT_FOUND)
