# Generated by Django 5.1.15 on 2026-06-10

"""Populate order_number for existing rows, then enforce uniqueness."""

import uuid

from django.db import migrations, models


def populate_order_numbers(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.filter(order_number__isnull=True):
        order.order_number = uuid.uuid4()
        order.save(update_fields=["order_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_order_number_order_order_total_non_negative_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_order_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
