# Generated by Django 5.1.15 on 2026-06-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_shipping_cost_order_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_request_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
