# Generated by Django 5.1.15 on 2026-06-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_warehouse_warehousestock'),
        ('orders', '0010_add_refund_request_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.warehouse'),
        ),
    ]
