# Generated by Django 5.1.15 on 2026-06-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_add_order_currency_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
