# Generated by Django 5.1.15 on 2026-06-26 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_product_flags"),
        ("orders", "0016_add_order_status_created_at_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["guest_email"], name="orders_orde_guest_e_5522f9_idx"),
        ),
    ]
