# Generated by Django 5.1.15 on 2026-06-26 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_product_flags"),
        ("orders", "0017_add_order_guest_email_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["stripe_session_id"], name="orders_orde_stripe__efc29a_idx"),
        ),
    ]
