# Generated by Django 5.1.15 on 2026-06-26 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_review_catalog_rev_status_9a5323_idx_and_more"),
        ("orders", "0018_add_order_stripe_session_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="orders_orde_user_id_aab4c7_idx"
            ),
        ),
    ]
