# Generated by Django 5.1.15 on 2026-06-18 06:08

from django.db import migrations


def auto_approve_existing(apps, schema_editor):
    Review = apps.get_model("catalog", "Review")
    Review.objects.update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_review_status"),
    ]

    operations = [
        migrations.RunPython(auto_approve_existing, reverse_code=migrations.RunPython.noop),
    ]
