# Generated by Django 5.1.15 on 2026-06-26 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_product_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["status", "-created_at"], name="catalog_rev_status_9a5323_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user"], name="catalog_rev_user_id_82176f_idx"),
        ),
        migrations.AddIndex(
            model_name="warehousestock",
            index=models.Index(
                fields=["product", "variant"], name="catalog_war_product_467bd8_idx"
            ),
        ),
    ]
