# Generated by Django 5.1.15 on 2026-06-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_email_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
