# Generated by Django 5.1.15 on 2026-06-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_email_verified"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["user"], name="accounts_ad_user_id_46db89_idx"),
        ),
    ]
